'use strict';

/**
 * @ngInject
 */
function Index(Logger, Faker) {
  Logger.debug('Index');
  // ViewModel
  var vm = this;

  vm.welcomeMessage = 'Welcome message generated by AngularJS';
  vm.items = Faker.getItems();
}

module.exports = Index;
